### Read all users
GET http://localhost:3002/api/v2/users


### Create a new user
POST http://localhost:3002/api/v2/users
Content-Type: application/json

{
    "username": "linlinlin",
    "email": "linlinlin@atsr.com",
    "password": "linlinlin"
}

### Update a user
PUT http://localhost:3002/api/v2/users/6a0a9665f29a5c68b4960509
Content-Type: application/json

{
    "username": "delete",
    "email": "delte@gmail.com",
    "password": "dddddddd"
}

### Delete a user
DELETE http://localhost:3002/api/v2/users/6a0b1201a930b9b7d4e862b1

### login user
POST http://localhost:3002/api/v2/users/login
Content-Type: application/json

{
  "email": "test11@atsr.com",
  "password": "test123456"
}