### Read all users
GET http://localhost:3002/api/v2/users


### Create a new user
POST http://localhost:3002/api/v2/users
Content-Type: application/json

{
    "username": "test3",
    "email": "test3@atsr.com",
    "password": "ttttttttt"
}

### Update a user
PUT http://localhost:3002/api/v2/users/6a0a9665f29a5c68b4960509
Content-Type: application/json

{
    "username": "delete",
    "email": "delte@gmail.com",
    "password": "dddddddd"
}

### Delete a user
DELETE http://localhost:3002/api/v2/users/6a0b1201a930b9b7d4e862b1
